### ISSUE TITLE
Expaining

### ISSUE THREAD

**Issue by Mastercopper2346** [Mastercopper2346/Pysch-Engine-Discord-News#2]
The reason i fake is to say this:

Don't complain about 14-year-old emos on the internet, it's pointless and just let them get banned

**Comment by Mastercopper2346** [comment]
My reason @Theoyeah

**Comment by Mastercopper2346** [comment]
Hello?

**Comment by Mastercopper2346** [comment]
@Theoyeah..?

**Comment by jimmyjamescool** [comment]
shut up bitch
![B2C0F440-C035-4170-B227-6C6CD57A9E03](https://user-images.githubusercontent.com/98002066/180287897-4cbaf442-5396-4aef-ab00-26152819d417.jpeg)

**Comment by Mastercopper2346** [comment]
No you cant control me

**Comment by Mastercopper2346** [comment]
Like how you cant control a 14 year old emo person

**Comment by Mastercopper2346** [comment]
@Theoyeah please respond

**Comment by Theoyeah** [comment]
...

**Comment by Mastercopper2346** [comment]
Also I have a brother

**Comment by Mastercopper2346** [comment]
That plays roblox all day

**Comment by Theoyeah** [comment]
> That plays roblox all day

Tf ???

**Comment by Theoyeah** [comment]
OK, i unbanned you, BUT THIS IS NOT A GOOD REASON TO unban you !

**Comment by Mastercopper2346** [comment]
Ok
